sonar.projectKey=flogo-test-project
sonar.projectName=Flogo Test Project
sonar.projectVersion=1.0.0
sonar.sources=flogo-apps
sonar.language=flogo
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.scm.exclusions.disabled=true
#sonar.token=<your-token-here>
